## 服务端口号
server:
  port: 8200

## 服务名称
spring:
  application:
    name: springcloud-api-order-impl

eureka:
  instance:
    ## 注册中心地址
    hostname: 127.0.0.1
    ## EurekaClient向EurekaServer发送心跳的间隔时间
    lease-renewal-interval-in-seconds: 1
    ## EurekaServer收到最后一次心跳之后的等待时间，单位秒。超过则剔除
    lease-expiration-duration-in-seconds: 2
  ###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/
    ###是否将自己注册到Eureka服务中
    register-with-eureka: true
    ###是否从Eureka中获取注册信息,检索服务信息
    fetch-registry: true
